"""
Database models using SQLAlchemy ORM.

All models are strictly typed and include proper relationships.
"""

from datetime import datetime
from typing import TYPE_CHECKING
from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    ForeignKey,
    create_engine,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
    sessionmaker,
)

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    """Base class for all database models."""
    pass


class Conversation(Base):
    """
    Conversation tracking table.
    
    Each conversation represents a unique chat session with a user.
    """
    
    __tablename__ = "conversations"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    telegram_user_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    telegram_chat_id: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )
    
    # Relationships
    messages: Mapped[list["Message"]] = relationship(
        "Message",
        back_populates="conversation",
        cascade="all, delete-orphan",
        lazy="selectin"
    )
    image_versions: Mapped[list["ImageVersion"]] = relationship(
        "ImageVersion",
        back_populates="conversation",
        cascade="all, delete-orphan",
        lazy="selectin"
    )
    generated_posts: Mapped[list["GeneratedPost"]] = relationship(
        "GeneratedPost",
        back_populates="conversation",
        cascade="all, delete-orphan",
        lazy="selectin"
    )
    
    def __repr__(self) -> str:
        return f"<Conversation(id={self.id}, user={self.telegram_user_id})>"


class Message(Base):
    """
    Message history table.
    
    Stores all messages (user and assistant) in a conversation.
    """
    
    __tablename__ = "messages"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    message_type: Mapped[str] = mapped_column(String(20), default="text", nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )
    
    # Relationships
    conversation: Mapped["Conversation"] = relationship(
        "Conversation",
        back_populates="messages"
    )
    
    def __repr__(self) -> str:
        return f"<Message(id={self.id}, role={self.role})>"


class ImageVersion(Base):
    """
    Image version tracking table.
    
    Stores metadata for each image edit operation, enabling version control.
    """
    
    __tablename__ = "image_versions"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    original_image_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    drive_file_id: Mapped[str] = mapped_column(String(255), nullable=False)
    drive_file_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    imagebb_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    replicate_output_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    edit_instruction: Mapped[str] = mapped_column(Text, nullable=False)
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )
    
    # Relationships
    conversation: Mapped["Conversation"] = relationship(
        "Conversation",
        back_populates="image_versions"
    )
    
    def __repr__(self) -> str:
        return f"<ImageVersion(id={self.id}, version={self.version_number})>"


class GeneratedPost(Base):
    """
    Generated post tracking table.
    
    Stores all posts generated by the system for analytics and history.
    """
    
    __tablename__ = "generated_posts"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    platform: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )
    
    # Relationships
    conversation: Mapped["Conversation"] = relationship(
        "Conversation",
        back_populates="generated_posts"
    )
    
    def __repr__(self) -> str:
        return f"<GeneratedPost(id={self.id}, platform={self.platform})>"


class DatabaseManager:
    """Manages database connections and sessions."""
    
    def __init__(self, database_url: str, echo: bool = False):
        """
        Initialize database manager.
        
        Args:
            database_url: SQLAlchemy database URL
            echo: Whether to log SQL statements
        """
        self.engine = create_engine(database_url, echo=echo)
        self.SessionLocal = sessionmaker(
            autocommit=False,
            autoflush=False,
            bind=self.engine
        )
    
    def create_tables(self) -> None:
        """Create all database tables."""
        Base.metadata.create_all(bind=self.engine)
    
    def drop_tables(self) -> None:
        """Drop all database tables (use with caution)."""
        Base.metadata.drop_all(bind=self.engine)
    
    def get_session(self) -> "Session":
        """
        Get a new database session.
        
        Returns:
            SQLAlchemy session
        """
        return self.SessionLocal()
